export const selectOptions = [
  { label: "건강기능식품 정보", value: "HEALTH_FOOD_INFO" },
  { label: "기업정보", value: "COMPANY_INFO" },
  { label: "관광사진", value: "TOUR_PHOTO" },
  { label: "산 정보", value: "MOUNTAIN_INFO" },
  { label: "HACCP 제품 정보", value: "HACCP_PRODUCT_INFO" },
  // router에 추가해야함
  { label: "행정동별 인구 정보", value: "POPULATION_INFO" },
  { label: "국가별 정보", value: "COUNTRY_INFO" },
  { label: "관광정보", value: "TOUR_INFO" },
  { label: "", value: "" },
  { label: "", value: "" },
  { label: "", value: "" },
  { label: "", value: "" },
  { label: "", value: "" },
  { label: "", value: "" },
  { label: "", value: "" },
  { label: "", value: "" },
  { label: "", value: "" },
  { label: "", value: "" },
  { label: "", value: "" },
  { label: "", value: "" },
  { label: "", value: "" },
  { label: "", value: "" },
  { label: "", value: "" },
  { label: "", value: "" },
  { label: "", value: "" },
  { label: "", value: "" },
  { label: "", value: "" },
  { label: "", value: "" },
  { label: "", value: "" },
  { label: "", value: "" },
  { label: "", value: "" },
  { label: "", value: "" }
];
